//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageClient.MessageReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageReference.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/sendMsg", ReplyAction="http://tempuri.org/IMessageService/sendMsgResponse")]
        void sendMsg(string senderID, string receiverID, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/sendMsg", ReplyAction="http://tempuri.org/IMessageService/sendMsgResponse")]
        System.Threading.Tasks.Task sendMsgAsync(string senderID, string receiverID, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/receiveMsg", ReplyAction="http://tempuri.org/IMessageService/receiveMsgResponse")]
        string[] receiveMsg(string receiverID, bool purge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/receiveMsg", ReplyAction="http://tempuri.org/IMessageService/receiveMsgResponse")]
        System.Threading.Tasks.Task<string[]> receiveMsgAsync(string receiverID, bool purge);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : MessageClient.MessageReference.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<MessageClient.MessageReference.IMessageService>, MessageClient.MessageReference.IMessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMsg(string senderID, string receiverID, string msg) {
            base.Channel.sendMsg(senderID, receiverID, msg);
        }
        
        public System.Threading.Tasks.Task sendMsgAsync(string senderID, string receiverID, string msg) {
            return base.Channel.sendMsgAsync(senderID, receiverID, msg);
        }
        
        public string[] receiveMsg(string receiverID, bool purge) {
            return base.Channel.receiveMsg(receiverID, purge);
        }
        
        public System.Threading.Tasks.Task<string[]> receiveMsgAsync(string receiverID, bool purge) {
            return base.Channel.receiveMsgAsync(receiverID, purge);
        }
    }
}
